# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Formats python files using black
        language_version: python3.6
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: insert-license
        name: Add licence for all XML, md files
        files: \.xml$|\.md$
        exclude: ^\.github/.*$
        args:
          - --comment-style
          - <!--| | -->
      - id: insert-license
        name: Add licence for all .pig files
        files: \.pig$
        args:
          - --comment-style
          - "-- "
      - id: insert-license
        name: Add licence for all python/yaml/property files
        files: \.py$|\.properties$|\.yaml$|\.yml$
      - id: insert-license
        name: Add licence for all Jinja templates
        files: \.tpl$
        args:
          - --comment-style
          - "{# | | #}"
      - id: forbid-tabs
  - repo: local
    hooks:
      - id: yamllint
        name: Check yaml files with yamllint
        entry: yamllint -c yamllint-config.yml .
        language: python
        types: [file, yaml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: git://github.com/luismayta/pre-commit-mypy
    rev: 0.1.1
    hooks:
      - id: mypy
        name: Checks typing annotations consistency with mypy
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
      - id: pylint
        name: Checks for common programming errors with pylint
  - repo: https://github.com/thlorenz/doctoc.git
    rev: v1.4.0
    hooks:
      - id: doctoc
        files: ^README\.md|CONTRIBUTING\.md$
        args:
          - "--maxlevel"
          - "2"
  - repo: local
    hooks:
      - id: autoflake
        name: Autoflake - removes unused imports and variables
        entry: autoflake
        language: python
        files: \.py$
        args: ['--in-place', '--remove-all-unused-imports',
               '--remove-unused-variable', '--recursive']
      - id: pytest
        name: Runs all unit tests with pytest
        entry: ./bin/o2a-run-all-unit-tests
        language: script
        pass_filenames: false
        stages: ['push']
        always_run: true
      - id: check-bash-syntax
        name: Check Shell scripts syntax corectness
        language: docker_image
        entry: koalaman/shellcheck:stable -e SC1091 -e SC2181
        types: [shell]
      - id: validate-all-workflows
        name: Validates all oozie workflows
        language: system
        entry: ./bin/o2a-validate-all-workflows
        files: \workflow.xml$
